name: CI
on:
  pull_request:
    branches:
      - main
      - development # This will be used later

jobs:
  flutter_test:
    name: Flutter test and build
    runs-on: ubuntu-latest
    steps:
      # Packages used to work
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test # No tests yet since there is nothing to test.
      
  # build_ios:
  #   name: Building Deposit app (iOS)
  #   needs: [flutter_test]
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v3
  #       with:
  #         java-version: '12.x'
  #     - uses: subosito/flutter-action@v3
  #       with:
  #         channel: "stable"
  #     - run: flutter pub get
  #     - run: flutter analyze
  #     - run: flutter clean
  #     - run: flutter build ios --no-codesign

  release_android:
    name: Building Deposit App (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release
      - uses: ncipollo/release-action@v2
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
